version: '3.8'

services:
  web:
    build: .
    container_name: event_app_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@db:5432/ticket
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app/src
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      sh -c "alembic upgrade head &&
             uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
  db:
    image: postgres:15-alpine
    container_name: event_app_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_DB: ticket
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ticket"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: event_app_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: