"""create reviews table

Revision ID: 05662b2ab3cc
Revises: 7262dd1d690f
Create Date: 2026-08-20 11:21:59.309508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05662b2ab3cc'
down_revision: Union[str, Sequence[str], None] = '7262dd1d690f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('reviews_event_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_author_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_author_id_fkey'), 'reviews', 'users', ['author_id'], ['id'])
    op.create_foreign_key(op.f('reviews_event_id_fkey'), 'reviews', 'events', ['event_id'], ['id'])
    op.drop_column('reviews', 'created_at')
    # ### end Alembic commands ###
