"""create tickets table

Revision ID: 2393a145d255
Revises: 5e7a0d60d247
Create Date: 2026-08-13 16:16:51.523044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2393a145d255'
down_revision: Union[str, Sequence[str], None] = '5e7a0d60d247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tickets_uuid_key'), 'tickets', type_='unique')
    op.create_index(op.f('ix_tickets_uuid'), 'tickets', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_uuid'), table_name='tickets')
    op.create_unique_constraint(op.f('tickets_uuid_key'), 'tickets', ['uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
