"""add event statistics columns

Revision ID: 5e7a0d60d247
Revises: 697618ed0986
Create Date: 2026-08-12 15:10:41.022635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7a0d60d247'
down_revision: Union[str, Sequence[str], None] = '697618ed0986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('tickets_sold', sa.Integer(), nullable=False))
    op.add_column('events', sa.Column('available_seats', sa.Integer(), nullable=False))
    op.add_column('events', sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('events', sa.Column('views', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'views')
    op.drop_column('events', 'avg_rating')
    op.drop_column('events', 'available_seats')
    op.drop_column('events', 'tickets_sold')
    # ### end Alembic commands ###
